Merge in 72252, 72681, 72759, 73371 (<rdar://problem/6974792>):
------------------------------------------------------------------------
r72252 | zhongxingxu | 2009-05-22 01:38:27 -0700 (Fri, 22 May 2009) | 2 lines

Pull EmitRecord() out of loop. It should be called only once.

------------------------------------------------------------------------

------------------------------------------------------------------------
r72681 | zhongxingxu | 2009-05-31 17:49:11 -0700 (Sun, 31 May 2009) | 2 lines

Use a reference to modify the DeclIDs map.

------------------------------------------------------------------------

------------------------------------------------------------------------
r72759 | zhongxingxu | 2009-06-03 02:23:28 -0700 (Wed, 03 Jun 2009) | 2 lines

emit ORIGINAL_FILE_NAME record ID to blockinfo block.

------------------------------------------------------------------------

------------------------------------------------------------------------
r73371 | lattner | 2009-06-14 21:35:16 -0700 (Sun, 14 Jun 2009) | 6 lines

If PCH refers to a file that doesn't exist anymore, emit a nice error
like:
fatal error: could not find file '1.h' referenced by PCH file
instead of aborting with an assertion failure, PR4219


------------------------------------------------------------------------

llvm-svn: 73493